backend:
  # Choose the backend you prefer (GitHub, GitLab, BitBucket)
  # Reference: https://www.netlifycms.org/docs/authentication-backends/
  name: github
  branch: master
  repo: MartinRdw/gridsome-starter-netlifycms

media_folder: "static/images"
public_folder: "static/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Role", name: "author_role", widget: "string"}
      - {label: "Author Image", name: "author_image", widget: "image"}
      - {label: "Preview Image", name: "preview_image", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Title (SEO)", name: "title_seo", widget: "string"}
      - {label: "Description (SEO)", name: "description_seo", widget: "string"}
      - {label: "Twitter Card (SEO)", name: "twitter_card", widget: "image"}

  - name: "data"
    label: "Data"
    files:
      - name: "about"
        label: "About"
        file: "src/data/About.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "About" }
          - name: "items"
            label: "Items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - name: "contact"
        label: "Contact"
        file: "src/data/Contact.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Contact" }
          - { label: "Description", name: "description", widget: "text" }

      - name: "hero"
        label: "Hero"
        file: "src/data/Hero.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - name: "portfolio"
        label: "Portfolio"
        file: "src/data/Portfolio.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Portfolio" }
          - name: "items"
            label: "Work"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

      - name: "socialmedia"
        label: "Social Media"
        file: "src/data/SocialMedia.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Social Media" }
          - name: "items"
            label: "Social Media"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
